### ISSUE TITLE
Swipeable for Vertical Swiper

### ISSUE THREAD

**Issue by zachgibson** [software-mansion/react-native-gesture-handler#115]
React Native Android doesn’t support the `pagingEnabled` property for vertical scroll views, only horizontal ones. What do you think about this feature for React Native Gesture Handler?

**Comment by kmagiera** [comment]
Hey @zachgibson! Yeah, I think this is sth we can consider experimenting with. Would love to see this being implemented as a module. There is some similar work done by @satya164 here https://github.com/react-native-community/react-native-tab-view/pull/376 also for vertical pagers but since it uses GestureHandler under the hood it should be easy to modify it to support vertical swiping as well.

**Comment by zachgibson** [comment]
Yo @kmagiera! Do you mean a separate module or including it in Swipeable? I might’ve missed it in this repo but what are the plans for components like Swipeable once this in the core of RN?

**Comment by jkadamczyk** [comment]
Due to the fact that this issue is more than 2 years old I am closing it. have a good day! 🙂
