### ISSUE TITLE
RNGestureHandlerRootView intercepting all the touches

### ISSUE THREAD

**Issue by night2tl** [software-mansion/react-native-gesture-handler#1180]
## Description

I'm writing a tool that would identify clicks on views, (a native Android SDK) - for that, I'm setting for each view I want to catch his clicks, a touchDelegate and sometimes even an onTouchListener.
When I'm using your library, the touchDelegates and touchListeners aren't getting invoked when an RNGestureHandlerRootView is above them in the view hierarchy. I guess that's happening because you're intercepting the touch events.

My question would be the following: How could I actually get the views on which I set the touchDelegate/touchListener to receive the clicks and still be using your library?

- React Native:
- React Native Gesture Handler:

**Comment by jakub-gonet** [comment]
At the moment we don't support this possibility because after handling event we're [returning `true` in the `dispatchTouchEvent` of the root view](https://github.com/software-mansion/react-native-gesture-handler/blob/e64d6fcf245220a3ee5273bb5e111a965bb5b991/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootView.java#L62-L65). Android integration with RNGH needs changing the root view, maybe you could try creating your own wrapper and pass touches to RNGH after you're done with them?
