### ISSUE TITLE
PanGestureHandler gesture is not canceled right away after being disabled

### ISSUE THREAD

**Issue by rubengt01** [software-mansion/react-native-gesture-handler#1260]
## Description

Trying to drag a view inside a ScrollView (`PanGestureHandler` inside a `ScrollView`). I am disabling `PanGestureHandler` (as the documentation recommends) to allow scrolling if the gesture doesn't start in the right place. It works great on iOS but the behavior is not consistent on Android. If the user flings quickly, then `onGestureEvent` and `onHandlerStateChange` is called with `State.ACTIVE` even when the gesture handler is disabled.

### Screenshots

```
SM-A515F: handleEvent) state: State.BEGAN
SM-A515F: -> disabledDrag {x:309.4754333496094, y: 214.28274536132812}
SM-A515F: render) enabledDrag: false
SM-A515F: handleEvent) state: State.ACTIVE
SM-A515F: -> set new position {x:311.88970947265625, y: 195.42431640625}
SM-A515F: handleEvent) state: State.ACTIVE
SM-A515F: -> set new position {x:311.88970947265625, y: 195.42431640625}
SM-A515F: handleEvent) state: State.CANCELLED
SM-A515F: -> pan ended
SM-A515F: render) enabledDrag: true
```

## Steps To Reproduce

1. Run the snack link on a physical Android device
2. Do a fast fling on the right side of the yellow component to scroll down. The finger should touch the screen very quickly to see the issue

### Expected behavior

- The PanGestureHandler should be canceled because it was disabled.
- ScrollView should scroll

### Actual behavior

- handleEvent is called with `State.ACTIVE` and the `ScrollView` doesn't scroll

## Snack or minimal code example

Snack [link](https://snack.expo.io/@rubengt01/pangesturehandler-not-canceling-gesture)

## Package versions

"react": "16.13.1"
"react-native": "0.63.3"
"react-native-gesture-handler": "1.9.0"

**Comment by j-piasecki** [comment]
Hi! You could use [touch events](https://docs.swmansion.com/react-native-gesture-handler/docs/api/gestures/touch-events) introduced in Gesture Handler 2.0 with Reanimated to accomplish this effect. You can simply [fail](https://docs.swmansion.com/react-native-gesture-handler/docs/api/gestures/state-manager#fail) the gesture if the pointer isn't in the right place to start the gesture. Because it happens synchronously, there will be no delay between failing the gesture and it actually stopping.
