### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by robertherber** [software-mansion/react-native-gesture-handler#1261]
To make it easier to contribute it’d be great if the project was in TypeScript.

**Comment by jakub-gonet** [comment]
There's ongoing effort to rewrite this in TS:
https://github.com/software-mansion/react-native-gesture-handler/tree/%40wolewicki/configure-ts

We should open the PR in the near future, but it'll require some testing & probably introduce breaking changes (declaration file is nearly 4 years old and TS evolved since then 😞)
