### ISSUE TITLE
If expo react native debugger open, swipe doesn't respond in IOS

### ISSUE THREAD

**Issue by ivanfuzuli** [software-mansion/react-native-gesture-handler#1302]
## Description
When open react native debugger open, swipe doesn't response in ios device and simulators.

### Screenshots
<img width="300" alt="Screen Shot 2021-01-08 at 20 51 00" src="https://user-images.githubusercontent.com/53147473/104047765-3b604600-51f3-11eb-864b-b21e8cb42a6c.png">

## Steps To Reproduce

1. Open react native debugger in ios emulator or device.
2. Swipe right or left
3. Swipe doesn't happen
4. Close react native debugger
5. Everything is fine

### Expected behavior
Animation will start on swipe.
### Actual behavior
Animation doesn't start on swipe.
## Snack or minimal code example
```
import React from "react";

import { PanGestureHandler }  from 'react-native-gesture-handler';
import  Animated from "react-native-reanimated";

const {
  Value, event,  set
} = Animated;


export default () => {
  const translationX = new Value(0);

  return (
<PanGestureHandler
  onGestureEvent={ event([
    {
      nativeEvent: {
        translationX: x => set(translationX, x),
      },
    },
  ])}>
      <Animated.View style={{height: 300, width: 300, backgroundColor: 'red', transform: [{translateX: translationX}]}}>
      </Animated.View>
    </PanGestureHandler>
  );
};
```

## Package versions

- React: "16.13.1"
- Expo: "40.0.0"
- React Native Gesture Handler: "1.8.0"

**Comment by yolpsoftware** [comment]
Also having this issue since updating to Expo 40. Upgrading to `react-native-gesture-handler` `1.9.0` did not resolve the issue.

`TapGestureHandler` is also affected.

**Comment by mackenziekira** [comment]
Also seeing this issue after upgrading from Expo 37 to Expo 40. Causes `react-navigation` drawer to not respond to swipes or taps. Seeing the issue on iOS 13.6, iPhone 8 in a managed app, but not on the simulator unless remote debugging is enabled.

```
"react-native": "0.63.2",
"react-native-gesture-handler": "1.9.0",
"react-native-reanimated": "1.13.2",
"@react-navigation/drawer": "5.11.4",
```

Was able to fix by forking `react-navigation` with a change that passes a callback to `PanGestureHandler` and `TapGestureHandler` instead of a `react-native-reanimated` `event`: https://github.com/mackenziekira/react-navigation/commit/a9eaa6123d052651371977021bb2928bae218e26

possibly related: https://github.com/expo/expo/issues/11475

**Comment by omid-ebrahimi** [comment]
I upgraded `react-native-gesture-handler` to version 1.10.0 and `react-native-tab-view` doesn't respond to swipes anymore.

**Comment by jakub-gonet** [comment]
@omid-ebrahimi, upgrade it to 1.10.1, there was a patch fixing those issues.

**Comment by yolpsoftware** [comment]
@jakub-gonet in the Expo Managed Workflow I cannot upgrade to 1.10.1 - is there a workaround?

**Comment by jakub-gonet** [comment]
Expo SDK 41 should use the newest gesture handler. Keep in mind this was a response to @omid-ebrahimi, in 1.10.0 there was a bug that prevented RNGH from working properly and it's not related to the main issue.

**Comment by yolpsoftware** [comment]
@jakub-gonet I see, thanks.

So this bug is still open, without a workaround.

**Comment by WoLewicki** [comment]
It looks like a problem with `react-native-reanimated`, since now the view does not even appear when it is `Animated.View`. It is probably due to limitations of that library, see: https://docs.swmansion.com/react-native-reanimated/docs/2.0.0/#known-problems-and-limitations. I will close this issue then. Feel free to comment here if I am wrong and we can always reopen it.

**Comment by yolpsoftware** [comment]
Pretty sure the issue was also occurring when the views were normal views, not `Animated` ones.

And, why would the "known problems and limitations" of version 2.0.0 mean that the View does not appear? The current version is 2.3.0.
