### ISSUE TITLE
[WEB] PanGestureHandler -  Not working in Firefox

### ISSUE THREAD

**Issue by davidbiller** [software-mansion/react-native-gesture-handler#1322]
just check the App here: https://www.aivy.app/funnel

1. click on "JETZT STARTEN" 
2. click on "Hochstapler" Challenge. 
3. Check in Safari/Chrome and than in Firefox. 

In Firefox sometimes if we drag a "stone" very fast, its moving a bit.

**Comment by davidbiller** [comment]
@EvanBacon can you check this pls? I dont know what I can do here.

**Comment by jakub-gonet** [comment]
Hi, could you submit a smaller repro example? 
Although I can see this behavior on FF I can't do anything about it since I don't know how do you use PanGH. This may be as well bug of Hammerjs which we use underneath the web version of RNGH.

Closing until more info is given.
(Also, next time try sticking to the issue template, thanks!)
