### ISSUE TITLE
Native Touchable* not working anymore (1.10.0)

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-gesture-handler#1338]
## Description

Since the 1.10.0 upgrade the `Touchable*` components are not working anymore on Android, meaning they don't switch states, don't show visual feedback, and don't call onPress events. 

Everything is working as expected on iOS.

## Steps To Reproduce

1. Use TouchableOpacity from RNGH in 1.9.0, note how it works
2. Use TouchableOpacity from RNGH in 1.10.0, note how it doesn't work anymore

### Expected behavior

I expect it to _work_.

### Actual behavior

It doesn't _work_.

## Snack or minimal code example

```jsx
import React from "react";
import "react-native-gesture-handler";
import { Text, View } from "react-native";
import { Navigation } from "react-native-navigation";
import { PressableOpacity } from "./src/common/components/pressables/PressableOpacity"; // <-- that's a RN <Pressable> with opacity effect
import {
  gestureHandlerRootHOC,
  TouchableOpacity,
} from "react-native-gesture-handler";

const App = () => {
  console.log("Re-rendering App...");
  return (
    <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
      <Text>Hello world!</Text>
      <PressableOpacity
        style={{ width: 100, height: 50, backgroundColor: "blue" }}
        onPress={() => console.log("js")}
      />
      <TouchableOpacity
        disabled={false}
        style={{ width: 100, height: 50, backgroundColor: "red" }}
        onPress={() => console.log("rngh")}
      />
    </View>
  );
};

Navigation.registerComponent(
  "Home",
  () => gestureHandlerRootHOC(App),
  () => App
);

Navigation.setRoot({
  root: {
    component: {
      name: "Home",
    },
  },
});
```

## Package versions

- React: 17.0.1
- React Native: 0.64.0-rc.3
- React Native Gesture Handler: 1.10.0

**Comment by jakub-gonet** [comment]
Could you prepare a more minimal repro that not uses anything except RN and RNGH?
Are you sure this regression isn't coming from RN64? I checked diff for android/ directory between 1.9.0 and 1.10.0 and found nothing. We mostly transitioned from JS to TS in this release and this shouldn't break anything.

Maybe RN is not picking up .android.tsx files? Do you have a standard setup for babel that uses `module:metro-react-native-babel-preset`?

**Comment by mrousavy** [comment]
1. On it
2. Well I also tested with RN 64 and RNGH 1.9.0 and it worked fine, so even if RN 64 made something incompatible, it probably should be fixed in RNGH
3. If it couldn't resolve the android.tsx import wouldn't it simply throw an import error or not render the component? In my case everything gets rendered correctly
4. Yes I'm using the `module:metro-react-native-babel-preset` preset

**Comment by jakub-gonet** [comment]
3. It'd fallback to the non-prefixed version.

You can test that by replacing the content of `src/GestureHandlerRootView.ts` with `src/GestureHandlerRootView.android.tsx` directly in the node_modules. The first one is reexporting view, the second one has some custom logic for Android.

**Comment by ahmadi-akbar** [comment]
same issue

**Comment by marcinkieruzel** [comment]
same here
1.10.0 makes TouchableOpacity not working – downgrading to 1.9.0 fixes the problem

**Comment by jakub-gonet** [comment]
@ahmadi-akbar, @marcinkieruzel, have you tested my assumption from [this comment](https://github.com/software-mansion/react-native-gesture-handler/issues/1338#issuecomment-775815760)?

**Comment by UNIDY2002** [comment]
@jakub-gonet It seems to be inappropriate to simply dump code with`JSX` syntax into a `.ts` file.
On the other hand, renaming `src/GestureHandlerRootView.ts` into `src/GestureHandlerRootView.tsx` can solve the problem.

**Comment by exneval** [comment]
@jakub-gonet it seems transitioned to TS really have issue in 1.10.0, just upgrade from 1.9.0, please do more checking, maybe start from @UNIDY2002 comment?

**Comment by bixou** [comment]
Same here since 1.10 : 

### Packages Versions

React : 16.13.1
React Native : 0.63.3
React Native Gesture Handler : 1.10.0

**Comment by jakub-gonet** [comment]
> @jakub-gonet It seems to be inappropriate to simply dump code withJSX syntax into a .ts file.
On the other hand, renaming src/GestureHandlerRootView.ts into src/GestureHandlerRootView.tsx can solve the problem (at least in my own repo, which also encountered this issue yesterday).

It doesn't really matter since the babel plugin is supposed to strip any ts annotations.
I'll test that, seems like maybe it only supports .tsx extension.

I'm assuming y'all use standard react-navigation setup for gesture handler?

**Comment by mrousavy** [comment]
@jakub-gonet I'm on react-native-navigation and I'm assuming the others are too, so it has to be a problem with the gesture handler root HoC. I'll see if I can find some time later to maybe test if it works without react-native-navigation (so without the HoC)

**Comment by yfunk** [comment]
@jakub-gonet @mrousavy I downgraded from `1.10` pretty quickly because of #1341, but I didn't notice any issues with Touchables not working on Android. I'm on React Native `0.63.4` with a standard `react-navigation` setup, so maybe this issue is somehow related to the setup with `react-native-navigation` (assuming other people with the issue are also using this library).

**Comment by aline-matos** [comment]
Same with `TouchableHighlight`

**Comment by jakub-gonet** [comment]
You can check if changes #1351 improve the situation for you.

**Comment by TheWirv** [comment]
I had a similar problem, where I provide a custom RNGH `TouchableNativeFeedback`-based `tabBarButton` to a React Navigation BottomTabBar on Android. Since 1.10.0 it looked like this.
![Screenshot_1613120208](https://user-images.githubusercontent.com/4397989/107748391-412cd800-6d19-11eb-8046-c7a5f9fbb29d.png)

But thanks to #1351 it looks the way it's supposed to again:
![Screenshot_1613120056](https://user-images.githubusercontent.com/4397989/107748432-51dd4e00-6d19-11eb-8c11-896cfc1f65a7.png)

Thx very much for the quick fix @jakub-gonet
