### ISSUE TITLE
 } as const; react-native-gesture-handler\src\State.ts: Unexpected token (10:5)

### ISSUE THREAD

**Issue by shuidaan** [software-mansion/react-native-gesture-handler#1344]
## Description

![image](https://user-images.githubusercontent.com/24624971/107449340-5de0d880-6b7e-11eb-9474-0fa341a37e81.png)

error SyntaxError: D:\rn\react-native-ble-demo\ble_central\node_modules\react-native-gesture-handler\src\State.ts: Unexpected token (10:5)
## Steps To Reproduce

1.

## Snack or minimal code example

   8 |   ACTIVE: 4,
   9 |   END: 5,
> 10 | } as const;
     |      ^
  11 | 
  12 | // eslint-disable-next-line @typescript-eslint/no-redeclare -- backward compatibility; it can be used as a type and as a value
  13 | export type State = typeof State[keyof typeof State];. Run CLI with --verbose flag for more details.
SyntaxError: D:\rn\react-native-ble-demo\ble_central\node_modules\react-native-gesture-handler\src\State.ts: Unexpected token (10:5)

## Package versions

- React:
- React Native:
- React Native Gesture Handler:
  "buffer": "^6.0.3",
    "react": "17.0.1",
    "react-native": "0.63.4",
    "react-native-ble-plx": "^2.0.2",
    "react-native-device-info": "^8.0.1",
    "react-native-gesture-handler": "^1.10.0",

**Comment by jakub-gonet** [comment]
Do you use custom babel setup? metro-react-native-babel-preset should handle TS files as source.

**Comment by f-roland** [comment]
> Do you use custom babel setup? metro-react-native-babel-preset should handle TS files as source.

it depends on your version of react-native and the version of the tooling used. On older versions of RN (at least 0.59 from what I can tell), it will break. 
This should have been a major version update, as you are de facto changing the minimum supported version of RN. Builds with older versions of RN if this lib is used in a project with version `^1.x.x` and node picks up this minor update

**Comment by jakub-gonet** [comment]
> This should have been a major version update, as you are de facto changing the minimum supported version of RN. Builds with older versions of RN will break if this lib is used in a project with version ^1.x.x and node picks up this minor update

We adopted the Expo versioning system – changes changing native code are minor, js changes are patches (there are exceptions, we rewrote RNGH from JS to TS and while this is technically not a native change we still bumped minor version). This system keeps major version bumps to changes in API. Removing support for older versions of RN isn't considered by us as breaking change (however, we try to support the broadest range of RN versions as possible). 0.59 is [nearly 2 years old](https://reactnative.dev/blog/2019/03/12/releasing-react-native-059) and we're about to see RN 0.64. [Here's a table](https://github.com/software-mansion/react-native-gesture-handler#react-native-support) showing RNGH support for RN versions.

Builds with older versions shouldn't break if lockfile is used.


That being said, the original author uses RN v0.63.4 which should transpile TS files automatically. That's why I asked if they use a custom babel setup – this shouldn't happen on a clean install of RN.

**Comment by f-roland** [comment]
fair enough - We still have the workaround to use either resolutions or change the dependency to a fixed version, this is what we recommended developers working on older versions of RN. Lock files are not always an option when projects are being generated on the fly in CI, where'd you'd have a list of dependencies with versions, but no lock file.

I'm saying 0.59 because I've seen a project with that version failing, but that doesn't mean more recent versions of RN are not affected.
