### ISSUE TITLE
Tab changes when tapping ScrollView which has shouldActivateOnStart={true}

### ISSUE THREAD

**Issue by viljark** [software-mansion/react-native-gesture-handler#1466]
**Current Behavior**

- `ScrollView` from `react-native-gesture-handler`
- Tab Navigator from `@react-navigation/material-top-tabs`
- my screen containts `ScrollView` which has `shouldActivateOnStart={true}` specified
- my screen is not first or last screen
- when I tap or try to scroll the `ScrollView`, the screen is changed

**Expected Behavior**

- no screen changing, `ScrollView` scrolls

**How to reproduce**
Happens on my Android 8 & 9

Snack: https://snack.expo.io/@viljark/tenacious-peach

Swipe to the second view, try to scroll the ScrollView

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| Android                      | 8 & 9
| react-native-gesture-handler | 1.10.2
| @react-navigation/native            | 5.9.4
| @react-navigation/material-top-tabs | 5.3.15
| react-native-tab-view               | 2.16.0
| react-native                        | React Native 0.63
| expo                                | SDK 41
| node                                | 10.15.3
| npm or yarn                         | npm

**Comment by j-piasecki** [comment]
Hi! This should be fixed by https://github.com/software-mansion/react-native-gesture-handler/pull/1796. The problem was happening becasue the `shouldActivateOnStart` was causing the `ScrollView` to cancel all other gestures, resulting in `PanGestureHandler` going to `CANCELLED` state without going through `BEGAN`, where the old state would be reset. So if you were swiping right into the screen, touching the scroll view would be treated by the Tab Navigator as you finishing swiping again.
