### ISSUE TITLE
`pointerEvents="box-none"` breaks gesture handling

### ISSUE THREAD

**Issue by hellsan631** [software-mansion/react-native-gesture-handler#1575]
## Description

On Android, adding `pointerEvents="box-none"` to a _child's_ view breaks gestures. Originally I thought this was a bug with `react-native-reanimated`, but i've been able to reproduce it without reanimated installed at all.

### Expected behavior

You should be able to use a PanGestureHandler with a child View with `pointerEvents="box-none"`. This is important with overlays and such.

### Actual behavior & steps to reproduce

1. Have a `<PanGestureHandler />` with a direct child that implements `<View pointerEvents="box-none" />`
2. The child must be the direct descendent of the `PanGestureHandler` (not a child's child.)
3. The child must also have a child view that defines some bounds (width/height) to touch. (this is interesting, as making the parent implement a height/width without a child, ios breaks as well.)
4. Try to use the gesture handler's `onGestureEvent`
5. `onGestureEvent` won't fire on android (ios works fine here)

## Snack or minimal code example

https://github.com/hellsan631/broken-pointer-events

## Package versions

- React Native: 0.64.2
- React Native Gesture Handler: 1.10.3 (latest) (also tried master branch)

## Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by jakub-gonet** [comment]
This is expected: Gesture handler doesn't create any views when adding touch handling and binds handlers to the component's child.

In your case, it binds to the view with pointerEvents="box-none" so it passes touches to its children (and there's none, so it stops traversing). [Here's the code that handles that.](https://github.com/software-mansion/react-native-gesture-handler/blob/master/android/lib/src/main/java/com/swmansion/gesturehandler/GestureHandlerOrchestrator.kt#L388-L393)

If anything, iOS should be fixed to respect this prop.

Could you describe your usecase? Maybe we can work around this.

**Comment by hellsan631** [comment]
Ah, sorry about the visibility, should be fixed now.

The use-case i've had was for a bottom drawer overlay for some video controls. There are some absolutely positioned elements, both parents and children, that relied on this behavior to pass down events, not getting in the way other other controls. 

I've kind of fixed this since, but the fact that iOS had such a different behavior threw me off. I agree with you, it would be great to be consistant here.

**Comment by mrousavy** [comment]
I'm having the same issue, posted a comment with a full code example here: https://github.com/software-mansion/react-native-gesture-handler/issues/1270#issuecomment-905674291

In my case, I have a custom native image view that overrides the Java methods `dispatchTouchEvent` and `onTouchEvent` to allow touches on transparent pixels to pass through. that's why it's parents (`View`s) have to have `box-none`, so they don't swallow the event if the custom native view refuses to handle them (transparent pixel was touched, `dispatchTouchEvent` returns false).

It's a bit of a complex use case, I know, let me know if you have any more questions or need help reproducing. I can also take a look at fixing this myself sometime next week
