### ISSUE TITLE
null is not an object (evaluating '_RNGestureHandlerModule.default.dropGestureHandler')

### ISSUE THREAD

**Issue by chillinncodin** [software-mansion/react-native-gesture-handler#1669]
Hello, i just update my reanimated library from 2.0.0 to beta version and this happened.

null is not an object (evaluating '_RNGestureHandlerModule.default.dropGestureHandler') (it was operating smoothly before)

Here is my code: 
![Screen Shot 2021-10-06 at 12 37 44](https://user-images.githubusercontent.com/91953499/136146258-54cd70d5-b374-475d-b5da-a5df393318d5.png)

**Comment by j-piasecki** [comment]
Hi, does this issue happen consistently or does it happen randomly?

**Comment by j-piasecki** [comment]
It is possible that this is the issue with Reanimated that should be fixed in the near future. You can try and apply [these changes](https://github.com/software-mansion/react-native-reanimated/pull/2512) to see if it fixes your problem.

**Comment by kmagiera** [comment]
hi @chillinncodin – as per @j-piasecki have you tried using the patch? If not, the patch since the time of that comment was merged to reanimated and was published as a part of reanimated@2.3. This should make it easier for you to try as the only thing you'll need to do is to upgrade reanimated (note that on Oct 19 when you said you upgraded the change was merged but not yet published to NPM)

If the issue still persist, we'd appreciate if you provided a working example of the issue. The code screenshot does not contain a full example but only a fragment of the app. We'd also prefer if you share code in a text form rather than an image. Thanks!
