### ISSUE TITLE
PinchGestureHandler does not work on Android

### ISSUE THREAD

**Issue by german970814** [software-mansion/react-native-gesture-handler#1709]
## Description
Android Pinch Gesture does not work properly. I'ven implemented a pinch to zoom like instagram feature, on iOS everything is working well, but on Android is not taking the interactions properly.

When I see the logs, on android start log event in a pinch gestures just tapping the component and not pinching. I've tried a lot of ways, setting a GestureHandlerRootView, changing versions but I cannot get work properly yet.

## Steps To Reproduce

1. Just create a component with PinchGestureHandler, try to log events, and you see different behavior between Android and iOS

### Expected behavior

Should work on android, at least some similar

### Actual behavior

Not working on android

## Snack or minimal code example

https://snack.expo.dev/@german21unicorns/pinch-android-error

## Package versions

- React: 16.13.1
- React Native: ~0.63.4
- React Native Gesture Handler: ~1.10.3

**Comment by j-piasecki** [comment]
Hi and thank you for the report! Since you mentioned `start` event, I assume you are using `useAnimatedGestureHandler` hook from Reanimated. In this case `onStart` is actually called when the handler moved to the `BEGAN` state which indeed differs between the platforms but it is due to differences in implementation and it is intended behavior.

That said, we are currently working on version 2.0 where `onStart` is called when the gesture activates and that would match your description. We hope to release it soon but I do not have a solid timeframe yet.

**Comment by german970814** [comment]
@j-piasecki there is some change I may do to get it work?

**Comment by j-piasecki** [comment]
Could you provide some code or steps to reproduce this problem?
