### ISSUE TITLE
[IOS]: "onStart" doesn't trigger by touching the element

### ISSUE THREAD

**Issue by LotfiOR** [software-mansion/react-native-gesture-handler#1716]
On IOS, "onStart" doesn't trigger by touching the element in question but rather after a making small movement. It should be an onTouch effect. ANDROID, onStart works perfectly.

- React:
- React Native:
- React Native Gesture Handler:

**Comment by j-piasecki** [comment]
Hi, thanks for the report! There is a chance that the issue you are describing is already fixed by one of these PRs: https://github.com/software-mansion/react-native-gesture-handler/pull/1682, https://github.com/software-mansion/react-native-gesture-handler/pull/1612, https://github.com/software-mansion/react-native-gesture-handler/pull/1611, https://github.com/software-mansion/react-native-gesture-handler/pull/1610. Those will be included in the next release, as well as the new API where the callback names are more reflecting of the state change that triggers them which should help with the problem.

We hope to release the RNGH 2.0 soon but I don't have a solid timeframe. I will close the issue for now and if your problem still persists in the 2.0 feel free to reopen it with more details.
