### ISSUE TITLE
Bug ScrollView inside TouchableOpacity

### ISSUE THREAD

**Issue by jthies73** [software-mansion/react-native-gesture-handler#1851]
## Description
when placing a ScrollView inside of a TouchableOpacity it is not possible to trigger the TouchableOpacity onPress event when clicking into the ScrollView. 

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web

## Steps To Reproduce

1. Create a TouchableOpacity
2. Create a ScrollView inside the TouchableOpacity
3. press inside the nested ScrollView to trigger the TouchableOpacity's onPress event 

### Expected behavior
onPress event gets triggered while still being able to scroll the ScrollView

### Actual behavior
onPress event does not get triggered but you are able to scroll the ScrollView

## Snack or minimal code example

snack does not yet support expo 44

## Package versions

- React: 17.0.1
- React Native: 0.64.3
- React Native Gesture Handler: 2.1.0
- React Native Reanimated: 2.3.1

**Comment by j-piasecki** [comment]
Hi! I believe this problem comes from how events are handled on iOS. In this case, when you wrap the ScrollView with TouchableOpacity, the ScrollView will consume every touch event, thus preventing TouchableOpacity from working (it's implemented using `UIControl` not `UIGestureRecognizer`).

In this case, you could swap the components around - instead of wrapping ScrollView with TouchableOpacity you can wrap TouchableOpacity with ScrollView. If that is not a viable solution for your use case, you may want to consider using Tap gesture instead of TouchableOpacity.

**Comment by jthies73** [comment]
Thank you very much for the answer! I will come back here to tell you if and how it worked out :-) 

Best regards
Jo

**Comment by datngotan-aavn** [comment]
hi, do you have the answer for this @jthies73?
