### ISSUE TITLE
TouchableOpacity stops working on react native 0.68.0

### ISSUE THREAD

**Issue by mikolajadamowicz** [software-mansion/react-native-gesture-handler#1999]
## Description

After upgrading to react native 0.68.0 TouchableOpacity stops working on android platform. You can check it by turning on Element Inspector with Touchables options. TouchableOpacity stops being touchable (react native vanilla's component works just fine) 

### Platforms

- [ ] iOS
- [X] Android - tested on real device only
- [ ] Web

## Steps To Reproduce

1.Open app
2. add view wrapped with TouchableOpacity
3. try to click on it

### Expected behavior
It should register the OnPress action
### Actual behavior
it does nothing

## Snack or minimal code example

```
import { Text } from 'react-native'
import { TouchableOpacity } from 'react-native-gesture-handler'

export default ({  title, style }) => (
  <TouchableOpacity style={style}>
    <Text>{title}</Text>
  </TouchableOpacity>
)

```

## Package versions

- React: 17.0.2
- React Native: 0.68.0
- React Native Gesture Handler: 2.3.2
- React Native Reanimated: 2.6.0

**Comment by j-piasecki** [comment]
Hi! I believe that `TouchableOpacity` doesn't work in Element Inspector because it captures all touch events to determine which view was selected, in fact all gestures don't work when Element Inspector is enabled as the Gesture Handler doesn't receive any touch events.

`TouchableOpacity` from React Native may work because the events not consumed by Element Inspector might be passed to the RN's gesture system, but it's just a guess.

Unfortunately, I don't think there's much we can do about it.

**Comment by mikolajadamowicz** [comment]
Sure, i'll make one tomorrow

**Comment by billnbell** [comment]
??

**Comment by mikolajadamowicz** [comment]
OK thanks for pointing that out @j-piasecki. As it turned out, react navigation was a part of the problem. `GestureHandlerRootView` is used in stack navigator but not in tab navigator. All i have to do, was wrapping main stack in `GestureHandlerRootView`. Using it higher in the tree (wrapping whole navigator or app.js) doesn't work in my app for some strange reason. We can close the issue now. It has been resolved.
