### ISSUE TITLE
[bug][ios] Touchables (all of them, including RectButton etc) prevent swiping in PagerView from react-native-pager-view

### ISSUE THREAD

**Issue by hirbod** [software-mansion/react-native-gesture-handler#2043]
## Description
When you use a Flatlist you will most likely import touchables from react-native-gesture-handler, I can't use them with `react-native-pager-view` because it breaks swiping. Guess there is some racing with the gestures going on. iOS only.

And yes, I tried `NativeViewGestureHandler` with `disallowInterruption` true/false and my App is wrapped with the RootView Component.

### Platforms

- [x] iOS
- [ ] Android
- [ ] Web

## Steps To Reproduce

1. Check my snack

### Expected behavior

Swiping should be possible

### Actual behavior

Swiping not possible

## Snack or minimal code example

https://snack.expo.dev/@hirbod/pager-view---rngh-touchables-issue?platform=ios

The green area is swipeable, the yellow area is not. Only the last one on Slide 3 is swipeable because it does use TouchableHighlight from react-native to demonstrate that this issue is caused by RNGH.

## Package versions

- React: 17.0.2
- React Native: 0.68.1
- React Native Gesture Handler: 2.4.2
- React Native Reanimated: 2.8.0

**Comment by j-piasecki** [comment]
I believe this may be the problem with `react-native-pager-view`, specifically [this line](https://github.com/callstack/react-native-pager-view/blob/master/ios/ReactNativePageView.m#L106). After changing it to `delaysContentTouches = YES`, the code from snack seems to be working as intended (that is, you can swipe between screens).

**Comment by j-piasecki** [comment]
My guess would be that the intention was to be consistent with React Native, as it sets this to NO on all `ScrollViews`, since it relies on its own touch system, but the description of the PR that added it (https://github.com/callstack/react-native-pager-view/pull/110) suggests that it was due to Gesture Handler. It seems a bit weird, as we set this property to YES on `ScrollViews` exported by GH:  https://github.com/software-mansion/react-native-gesture-handler/blob/faf6bbe0aa35f5650e5b0aca41a4d9c8c8ba8aa7/ios/Handlers/RNNativeViewHandler.mm#L115-L121
It should be safe to change, as it's used to determine whether the intent of the touch was to scroll or not (and YES is the default value - https://developer.apple.com/documentation/uikit/uiscrollview/1619398-delayscontenttouches?language=objc).

**Comment by hirbod** [comment]
Made a PR
https://github.com/callstack/react-native-pager-view/pull/563

Another attempt to fix this could also be to SubClass UIScrollView and only to implement

```objc
- (BOOL)touchesShouldCancelInContentView:(UIView *)view {
    return YES;
}
```

Than we should be able to set `delaysContentTouches` to NO

**Comment by hirbod** [comment]
Oh, this does has impact. Now Touchables from RN breaking, but RNGH works :D

**Comment by hirbod** [comment]
This was fixed upstream!
