### ISSUE TITLE
dragging a simple square or circle after one time does not work on android (it works on ios) in expo as well as android native

### ISSUE THREAD

**Issue by muneebejazz** [software-mansion/react-native-gesture-handler#2044]
## Description
Hi if you try to play it on snake or use your android to check it after one drag the square or ball does not move in the x and y direction . and even it does not console.log(), i dont know even if its a react-native-gesture-handler or even reanimated 2 issue . thanks. 
https://snack.expo.dev/@muneebejaz2022/58e65c

### Platforms

- [ ] iOS
- [x] Android
- [ ] Web

## Steps To Reproduce

1.

## Package versions

- React:
- React Native:
- React Native Gesture Handler:
- React Native Reanimated:

**Comment by j-piasecki** [comment]
Hi! I checked the snack and it looks like adding `style={{ flex: 1 }}` to `GestureHandlerRootView` solves the problem. It's because `GestureHandlerRootView` is used by Gesture Handler to intercept the touch events and in the snack it's not filling the entire screen. (You can check it's area by setting a background color to it).
