### ISSUE TITLE
Build failed due to missing folly_json and folly_futures

### ISSUE THREAD

**Issue by ErHarinderSingh** [software-mansion/react-native-gesture-handler#2051]
```
> > Task :react-native-gesture-handler:configureNdkBuildRelease[arm64-v8a] FAILED
> C/C++: fcntl(): Bad file descriptor
> C/C++: /Users/erharindersingh/Library/Android/sdk/ndk/21.4.7075529/build/core/build-binary.mk:651: Android NDK: Module rngesturehandler_modules depends on undefined modules: folly_json folly_futures    
```

I am on React Native RC 0.69 & new arch is enabled.

**Comment by ErHarinderSingh** [comment]
In React Native RC 0.69, they have removed it. I think from **react-native-gesture-handler**, it also needs to remove.

![Screenshot 2022-05-14 at 13 02 12](https://user-images.githubusercontent.com/22139572/168415855-b2e1e500-982d-4116-a02a-a5d41f30b967.png)

**Comment by j-piasecki** [comment]
Yes, the it will be fixed in the next release of Gesture Handler. For now you can use the same [patch](https://github.com/software-mansion/react-native-reanimated/blob/150e787d1101249122871128be5805c4fe288286/FabricExample/patches/react-native-gesture-handler+2.4.2.patch) the Reanimated team is using.
