### ISSUE TITLE
[Web] Text inside ScrollView cannot be selected due to the applied "user-select: none" css property

### ISSUE THREAD

**Issue by giacomocerquone** [software-mansion/react-native-gesture-handler#2211]
### Description

So as the title says, I cannot select any text on web when it's rendered within the rngh scrollview!

### Steps to reproduce

1. Render a scrollview from rngh
2. Render a text within it
3. Notice that you can't select the text.

### Snack or a link to a repository

https://snack.expo.dev/@mxmgcm/text-selection-rngh-scrollview-bug

### Gesture Handler version

2.5.0

### React Native version

0.69.0

### Platforms

Web

### Workflow

Expo managed workflow

### Acknowledgements

Yes

**Comment by adamhari** [comment]
This issue also affects screen content inside @react-navigation's drawer navigator when `useLegacyImplementation={false}` because the modern variant [is wrapped in a PanGestureHandler](https://github.com/react-navigation/react-navigation/blob/main/packages/drawer/src/views/modern/Drawer.tsx#L320).

**Comment by Warus15** [comment]
Hi 👋 [This PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2260) adds `userSelect: auto` to NativeViewGestureHandler that are in `ScrollView`

**Comment by Warus15** [comment]
Hello again @giacomocerquone. I forgot to mention one thing. As I can see you are using GestureHandler 2.5.0, but the PR that I've linked requires at least version 2.6.0, since new web implementation was introduced in that particular update. What i recommend is update your GestureHandler package to at least version 2.6.1, because it was mostly focused on web and contains many fixes. 

To enable new implementation, call `enableExperimentalWebImplementation()` in the root of your project ([see docs](https://docs.swmansion.com/react-native-gesture-handler/docs/installation#web))

**Comment by Warus15** [comment]
Hi again @giacomocerquone 👋

I'm back with some news. I've prepared another PR, which solves this problem using different approach. Please have a look at [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2280) and test, whether it solves your issue.

This approach gives more control to users, and also should allow solving problem with react-navigation, which was mentioned by @adamhari (though it still requires some changes in navigation)
