### ISSUE TITLE
Swipeable conflict with swipe to close screen( default on IOS) 

### ISSUE THREAD

**Issue by fukemy** [software-mansion/react-native-gesture-handler#2216]
### Description

I have chat app, and I wrapped message with Swipeable to reply, here is my code:
```
return (
        <GestureHandlerRootView>
          <Swipeable
            ref={updateRowRef}
            friction={2}
            rightThreshold={40}
            renderRightActions={renderRightAction}
            onSwipeableRightWillOpen={onSwipeWillOpen}
            onSwipeableOpen={onSwipeOpenAction}>
            {children}
          </Swipeable>
        </GestureHandlerRootView>
      )
```

### Steps to reproduce

1. Define chat app
2. Wrap message row by Swipeable

### Snack or a link to a repository

You can tested this problem only in REAL DEVICE

### Gesture Handler version

2.9.0

### React Native version

0.68.0

### Platforms

iOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Device

Real device

### Device model

all type of Iphone

### Acknowledgements

Yes

**Comment by fukemy** [comment]
YOU CAN NOT REPRODUCE THIS ISSUE WITH SNACK, JUST TEST ON REAL DEVICE

**Comment by j-piasecki** [comment]
I don't think I will be able to reproduce it based on the information you've provided, as I don't know how navigation in your application is implemented. Also, you might've made a typo in the Gesture Handler version, since the newest one is 2.6.0.

Could you prepare a repository with a reproduction? That would greatly help with resolving this issue.
