### ISSUE TITLE
Can't stop press event from bubbling when listening for double taps 

### ISSUE THREAD

**Issue by feRpicoral** [software-mansion/react-native-gesture-handler#2331]
### Description

I am using two `TapGestureHandler` to listen for single/double taps within a `View`:

```jsx
<TapGestureHandler
  onHandlerStateChange={onSingleTapEvent}
  waitFor={doubleTapRef}
>
  <TapGestureHandler
    ref={doubleTapRef}
    onHandlerStateChange={onDoubleTapEvent}
    numberOfTaps={2}
  >
    {props.children}
  </TapGestureHandler>
</TapGestureHandler>
```

The problem I am having is that if I have an element that has a press listener of its own within `props.children`, when I press that element, not only the element's listener is called, but `onSingleTapEvent` is also called.

I have tried using `event.preventDefault()` and `event.stopPropagation()` in the child event listener but that did not fix the problem.

The complete code for this listener is in this gist (50 lines):
https://gist.github.com/feRpicoral/ef4b5b679bcf616cc2303f6d65b73585

To exemplify:

Let's say I have the following element, which is wrapped with the `DoubleTap` wrapper (code on gist above):

<img width="532" alt="image" src="https://user-images.githubusercontent.com/30874402/204119363-923ed813-3727-4d48-b679-ea03529b4a63.png">

The grey block has a press listener. One would expect that when the grey block is clicked, **only** its `onPress` handler is called, and when any point of the black rectangle is clicked, the `onSingleTap` handler from `DoubleTap` would be invoked.

What is happening is that when one presses the grey block, both handlers are called.

### Steps to reproduce

1. Create a React Native project with Typescript
2. Install `react-native-gesture-handler`
3. Add this component to the project: https://gist.github.com/feRpicoral/ef4b5b679bcf616cc2303f6d65b73585
4. Create an element **with** a press handler and wrap this element with the element you created on step 3

### Snack or a link to a repository

https://gist.github.com/feRpicoral/ef4b5b679bcf616cc2303f6d65b73585

### Gesture Handler version

2.8.0

### React Native version

0.70.5

### Platforms

iOS

### Workflow

Expo bare workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
Hi! Unfortunately, depending on the view put inside the tap handlers, it's expected behavior in this case. I assume the views you've been trying were RN's touchables (or derived from them). That's because RN handles touch interaction mostly on the JS thread, while Gesture Handler relies on native behavior of the platform. I don't think it's possible to make them interoperable in a reasonable way.

The workaround you can try is wrapping the pressable component with a tap gesture and moving the interaction logic there. Here's a quick example:
```jsx
function Tappable(props) {
  const tap = Gesture.Tap().onStart(() => {
    props.onPress?.();
  });

  return (
    <GestureDetector gesture={tap}>
      {props.children}
    </GestureDetector>
  );
}
```

If you decide to go this way, keep in mind a few things:
- You need to use the new API to do this (GestureDetector instead of TapGestureHandler)
- If you have Reanimated installed, the callback will be automatically workletized. If you wish to run the callback on the JS thread, add `.runOnJS(true)` modifier to the gesture config i.e.: `Gesture.Tap().runOnJS(true).onStart(...)`
