### ISSUE TITLE
Swipeable not working when inside a UI Kitten ViewPager component

### ISSUE THREAD

**Issue by FezVrasta** [software-mansion/react-native-gesture-handler#2337]
### Description

I'm trying to use Swipeable on a component rendered in a UI Kitten ViewPager component, but all I get is the ViewPager page transition rather than the Swipeable one. Is there any way to stop the swipe gesture to propagate to the parent component maybe?

### Steps to reproduce

1. `<ViewPager><Swipeable /></ViewPager>`
2. Swipe on the Swipeable component

### Snack or a link to a repository

Can't make ui-kitten work on Expo

### Gesture Handler version

2.8.0

### React Native version

0.70.5

### Platforms

iOS

### Workflow

Expo managed workflow

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
It seems, UI Kitten's ViewPager uses the RN's touch responder system to handle swiping between views and it starts transition as soon as the finger moves more along the x-axis than on the y-axis, which in case of horizontal movement is near instant.

Gesture Handler is set up in such a way that it doesn't recognize gestures if the responder system has already started handling touch. Because of that, the ViewPager's transition starts immediately when you move the finger horizontally (you can actually verify that by swiping up/down a little before swiping left/right, if the vertical distance is large enough the swipeable will open).

I think the only sensible solution in this case is to modify the ViewPager's code and add a minimum distance required before the transition starts. You would need to modify [this](https://github.com/akveo/react-native-ui-kitten/blob/df96d0debd6ec24ad627cd531c7690ab0658b2f7/src/components/ui/viewPager/viewPager.component.tsx#L113) line to something like this:

```js
if (isHorizontalMove && Math.abs(state.dx) > 10) {
```

so that Gesture Handler can start handling the touch before the responder system.
