### ISSUE TITLE
Swipeable horizontal in a vertical Flatlist: too sensitive

### ISSUE THREAD

**Issue by pierroo** [software-mansion/react-native-gesture-handler#2380]
### Description

I have a vertical FlatList of items, each of those being wrapped in a Swipeable (horizontal).
It works well (except the performance issue already mentioned in other topics), however the issue is that sometimes upon scrolling, it accidentally triggers the horizontal scroll of those swipeable items.

It happens as soon as we scroll the flatlist too "diagonal" (thus not 100% vertical, which is rarely natural)

Any way to reduce the sensitivity of triggering the swipeable?
Or at least, to make sure it only happens on a truly horizontal gesture within the swipeable?

I already tried with all the frictions parameters, with Flatlist imported from RNGH, etc

### Steps to reproduce

1. Create a flatlist
2. each render item should be a swipeable from RNGH
3. scroll vertically, but sometimes with a more "diagonal" angle (even just 25degrees is enough to trigger the horizontal)
4. it triggers horizontal swipeable by mistake

### Snack or a link to a repository

(https://snack.expo.dev/YHU664VVC)

### Gesture Handler version

2.8.0

### React Native version

0.69.7

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

all

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
Could you try the above PR and check if the new `dragOffsetLeft` and `dragOffsetRight` props are enough to solve your problem?

**Comment by pierroo** [comment]
It works perfectly, thank you so much!
Any idea when it will be merged into an actual release, or should I patch-package for now?

**Comment by j-piasecki** [comment]
I'd guess it would be released in GH 2.10.0, probably in one or two weeks (although no promises there). I don't see a problem with using patch-package till then.

**Comment by VictorioMolina** [comment]
@j-piasecki Is there any other way to fix this problem without upgrading to 2.10.0? Because of my dependencias (expo sdk 47) I cannot use the `dragOffsetRight` property (upgrading react-native-gesture-handler > 2.9.0 breaks the EAS compilation for Expo 47).

**Comment by j-piasecki** [comment]
You can also use [`patch-package`](https://www.npmjs.com/package/patch-package) to apply the changes from the PR linked above in your project.

**Comment by anoopmm** [comment]
@j-piasecki I have a chat screen using FlashList and am implementing a swipe-to-reply functionality similar to WhatsApp for both left and right directions. However, the swipe is accidentally triggering when scrolling through messages because users don’t scroll the list perfectly vertically; their movement often has a slight angle, like a curve.

I have added an offset for both left and right swipes.
` dragOffsetFromLeftEdge={40}
  dragOffsetFromRightEdge={40}`

It works sometimes, but the left and right swipe still gets triggered. Is there a way to detect the swipe angle and prevent the left and right actions from appearing?
