### ISSUE TITLE
[2.10.0] Swipeable swiape don't prevent onPress

### ISSUE THREAD

**Issue by Bardiamist** [software-mansion/react-native-gesture-handler#2482]
### Description

I use Swipeable and wrapped content into TouchableOpacity. After update react-native-gesture-handler from 2.9.0 to 2.10.0 swipe don't prevents onPress of TouchableOpacity

### Steps to reproduce

Write Swipeable content in TouchableOpacity

### Snack or a link to a repository

https://snack.expo.dev/@bardiamist/swipeable-onpress

### Gesture Handler version

2.10.0

### React Native version

0.71.8

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14

### Acknowledgements

Yes

**Comment by GoktuqCan** [comment]
Hey @Bardiamist I had the same issue. Solved it by using **BaseButton** exported from react-native-gesture-handle. You can also use the **BaseButton** if you want the opacity effect.
https://docs.swmansion.com/react-native-gesture-handler/docs/api/components/buttons#basebutton

**Comment by TexxUkr** [comment]
To fix the issue it needs to use TouchableOpacity from react-native-gesture-handler rather than react-native.
in the problem code we have
`import { Text, View, StyleSheet, TouchableOpacity, Animated } from 'react-native';
import { RectButton, Swipeable } from 'react-native-gesture-handler';`
to fix the issue it needs to be
`import { Text, View, StyleSheet, Animated } from 'react-native';
import { RectButton, Swipeable, TouchableOpacity } from 'react-native-gesture-handler';`

**Comment by dannybit** [comment]
I am using the TouchableOpacity from react-native-gesture-handler but I am still seeing the same issue

**Comment by PierreCapo** [comment]
@dannybit on my side it works well if you place the `TouchableOpacity` from `react-native-gesture-handler` as first child of the `Swipeable` component 👍
