### ISSUE TITLE
Plugin with id 'com.facebook.react' not found.

### ISSUE THREAD

**Issue by Malik-Usman17** [software-mansion/react-native-gesture-handler#2499]
### Description

Till yesterday my project is running fine, but somehow from today morning, when I run the project, I am getting this error:

`FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\malik.usman\Desktop\Office\React Native Projects\lam-pro-app-dev\node_modules\react-native-gesture-handler\android\build.gradle' line: 62

* What went wrong:
A problem occurred evaluating project ':react-native-gesture-handler'.
> Plugin with id 'com.facebook.react' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s`

And note I didn't update anything. Researched everywhere, spending hours but didn't get any solution.

### Steps to reproduce

none

### Snack or a link to a repository

none

### Gesture Handler version

2.10.1

### React Native version

0.68.2

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by j-piasecki** [comment]
[The line that caused your build to fail](https://github.com/software-mansion/react-native-gesture-handler/blob/69b034a061455e746ee19fd343164511968bce00/android/build.gradle#L61-L63) is inside a conditional and runs only if you [enable the new architecture](https://github.com/software-mansion/react-native-gesture-handler/blob/69b034a061455e746ee19fd343164511968bce00/android/build.gradle#L24-L30). It shouldn't start randomly executing since you're saying you didn't change anything.

Besides reinstalling `node_modules` and clearing the gradle caches I don't have many ideas on how to tackle it. If those don't help you, would it be possible for you to share the repository or try to reproduce the error elsewhere so I could look into it?

**Comment by Malik-Usman17** [comment]
I tried both thing, deleting **node_modules**, reinstall and also delete the .gradle folder, but don't get the progress.

**Comment by m-bert** [comment]
Hi @Malik-Usman17! Do you still experience this issue? If so, could you provide a reproduction? As @j-piasecki said, it is not something that should break on its own.
