### ISSUE TITLE
Select Input not working (Refs) on Safari 

### ISSUE THREAD

**Issue by ArthurDias01** [software-mansion/react-native-gesture-handler#2673]
### Description

When using select components (drop down pickers) the after focusing an element on (Safari web) the element won't release the focus.

![261797283-7261afd3-9b12-4585-ad92-1dde85a7d430](https://github.com/software-mansion/react-native-gesture-handler/assets/83284629/daa98aea-6a3b-41fb-a8b5-33eba89b6be7)

https://github.com/react-navigation/react-navigation/issues/11546

We have tracked the problem to an specific commit on RNGH (Enable the new web implementation by default)
https://github.com/software-mansion/react-native-gesture-handler/commit/7799d7d74e832b85a286648451d812f14d2bb5de
### Steps to reproduce

1. install React Native Web 0.19.0
2. have a select element focused on a page/screen inside a drawer navigator* (react-navigation/drawer react-native-picker/picker)
3. Open it on Safari web
4. select the Select Element
5. the element breaks the flow

### Snack or a link to a repository

https://github.com/ArthurDias01/rngh-bug

### Gesture Handler version

2.10.0

### React Native version

0.72.6

### Platforms

Web

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Device

None

### Device model

Safari Web - macOS 14 Sonoma

### Acknowledgements

Yes

**Comment by ArthurDias01** [comment]
We found a fix for it. The only thing needed is to import 

```js
import { enableLegacyWebImplementation } from 'react-native-gesture-handler';

enableLegacyWebImplementation(true);
```

Reference fix: [docs/docs/installation.md](https://github.com/software-mansion/react-native-gesture-handler/blob/7799d7d74e832b85a286648451d812f14d2bb5de/docs/docs/installation.md#web)

**Comment by m-bert** [comment]
Hi @ArthurDias01! Thanks for pointing out this problem! 

First of all, it doesn't originate from the commit that you've mentioned - it seems that it is a bug that has been there since we reimplemented Gesture Handler for web. 

Second of all, enabling legacy implementation isn't a good fix - it may help with this problem, but other things may not work as they should. Also we do not support legacy web implementation since new one was officially released. 

However, if you're sure that legacy web implementation doesn't break anything in your app, you can use it while we are looking for a proper solution.

**Comment by m-bert** [comment]
Hi @ArthurDias01! Could you please check if [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2675) helps?

**Comment by ArthurDias01** [comment]
> Hi @ArthurDias01! Could you please check if [this PR](https://github.com/software-mansion/react-native-gesture-handler/pull/2675) helps?

Yes we could determine this is working as intended. Thanks!
