### ISSUE TITLE
new gesture api very slow rendering

### ISSUE THREAD

**Issue by Willham12** [software-mansion/react-native-gesture-handler#3195]
### Description

Bad performance with new gesture pan API. I have a similar circular slider with the same issue and with the old api no issues:
```js
<PanGestureHandler
enabled={!isDisabled}
maxPointers={1}
minDist={1}
onGestureEvent={handleGestureEvent}
onHandlerStateChange={handleGestureEvent}>
...
</PanGestureHandler>
```

### Steps to reproduce

Open the Snack and slider fast from left to right

### Snack or a link to a repository

https://snack.expo.dev/qFQCJMaMaZBreK0vOgQ0w

### Gesture Handler version

2.20.2

### React Native version

0.74.2

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

### Device

iOS simulator

### Device model

Iphone 15

### Acknowledgements

Yes

**Comment by Willham12** [comment]
Same result with better performance without using a state: https://snack.expo.dev/76p09SjKxZHh977msQHbj
And here ist a version with native slider package: https://snack.expo.dev/ViKIaC3sai2I8cVaN_IU2

try to slider very fast from left to right over and over again and you feel the difference.

**Comment by Willham12** [comment]
@m-bert but what if the progress depends on a state and this state can't replaced by a sharedValue?

**Comment by Willham12** [comment]
Nah, none of these solutions working for me. I have a very complex ui based on a circular slider and if release the slider onUpdate() still getting fired until the positions are processed. Same if the Component with the Gesture.Pan() are not updating by a state change. Based on the circular slider position i have to calculate a price based on a very complex price model and i don't now why but the new gesture api blocks the whole js thread. No issue with the old API.

**Comment by m-bert** [comment]
We've already showed that it is possible to create smooth slider. I've also provided 2 examples of how to do it. If your app has such level of complexity, then there's not much that we can do. Especially if you will use React `states`

**Comment by j-piasecki** [comment]
I'm not exactly sure what you mean by checking the log, could you provide an example with the old API where it works as you'd expect to compare to?

Also, I've noticed that you're using `.runOnJS` modifier on a gesture. This prevents it from being executed on the UI thread and adds a delay between receiving the event and applying the updated values to the views so that they are displayed on the screen. If you want to use a gesture to drive an animation you should do it on the UI thread and use [`runOnJS`](https://docs.swmansion.com/react-native-reanimated/docs/threading/runOnJS/) function from Reanimated to schedule things that cannot be executed on the UI thread (like state updates).

Coming back to your original snack, you shouldn't use state to drive animations. If you need other components to update in response to a gesture change, consider moving them to use `useAnimatedProps` or scheduling a state update in response to a shared value change in `useAnimatedReaction`.

**Comment by Willham12** [comment]
Please run the [example](https://snack.expo.dev/oQjqMz_sLClc9wXmmI9WW) and check the console logs. The onChange callback is still fire after the releasing the knob. It doesn't matter if you run it on ui thread. Check also line 45-49.

**Comment by Willham12** [comment]
If i removed a huge part of the underlying components tree then the new gesture api works as expected. Not sure why the legacy gesture api works better.

**Comment by Willham12** [comment]
After more investigation i notice that the JS frame rate drops down to 0 with new gesture api and with the legacy version its always above 20.

**Comment by Willham12** [comment]
@j-piasecki  here a video with the legacy PanGestureHandler:

https://github.com/user-attachments/assets/8f59163a-2db7-4459-8c3e-98eebf3c77bf

and here with the new Gesture.Pan() API:

https://github.com/user-attachments/assets/cdce411d-e4bb-448e-8dc9-14a5d63fd5dd

I can't share the real ui but the underlying computation is not simple but with the new gesture api the performance breaks down.
panGesture is wrapped into a useMemo and for the progress i'm using useDerivedValue.
Also with new gesture api i receive onUpdate events while the knob reached already the final position.

```ts
		const panGesture = useMemo(() => {
			return Gesture.Pan()
				.enabled(!isDisabled)
				.minDistance(1)
				.minPointers(1)
				.onBegin((event) => {
...
```

**Comment by j-piasecki** [comment]
I understand that you cannot post the entire code, but could you share some more details that may be important here?
- What's the component used to render the progress (SVG, Skia)?
- What's used to render the knob, since it seems to be working as expected?
- How is the knob animated?
- How is the progress animated?

**Comment by wwxxjj2233** [comment]
> 我知道您无法发布完整的代码，但您能否分享一些可能重要的细节？
> 
> * 用于呈现进度的组件是什么（SVG，Skia）？
> * 它看上去像预期的那样工作，用什么来渲染旋钮？
> * 旋钮如何动画化？
> * 进展如何活跃起来？

same problem.when I add "setTimeIndex(timeLineIndex)" in my code.My Animated  is very slow rendering.
  const onMoving = () =>{
    const scrollOffset = getScrollOffsetY() - startMovePageOffset.current;
    const timerTop = countTop.current + translateY.get() + scrollOffset;
    const currentTimerIndex = calculateIndexByTop(timerTop, blockTimes);
    let timeLineIndex = calculateEndAvailable(currentTimerIndex);
    setTimeIndex(timeLineIndex);//when i do this, the annimated is alow
    // I must use the index state to change my button Text
  };
  const panGesture = Gesture.Pan()
    .activeOffsetY(movable ? [0, 0] : [-40, 40])
    .hitSlop(IS_IOS ? { left: 0, height: 28, top: 0, right: 0 } : {})
    .enabled(!dragDisabled) 
    .onStart(() => {
      runOnJS(handlePanStart)();
    })
    .onChange(event => {
      if (!activeMove.get()) return;
      translateY.set(event.translationY);
      runOnJS(onMoving)();
    })
    .onFinalize(() => {
      runOnJS(handlePanEnd)();
    })
    .activateAfterLongPress(500);
