### ISSUE TITLE
Border does not appear in styling RectButton

### ISSUE THREAD

**Issue by yodaheis** [software-mansion/react-native-gesture-handler#477]
@pcooney10 I'm facing the issue of border not appearing on Android. It does work well on iOS though.
style props like **borderRadius works**, **but borderWidth, borderColor does not work on Android**

_Originally posted by @yodaheis in https://github.com/kmagiera/react-native-gesture-handler/issues/225#issuecomment-467333032_

I would like to bring to your attention border styling related issues on Android.
Border doesn't appear on Android while it works well on iOS.

*Environment*:
expo: 32.0.0

**Comment by vlkosinov** [comment]
Also there is no ability to apply `borderTopStartRadius`, `borderTopEndRadius`, `borderBottomStartRadius`, `borderBottomEndRadius` properties to RectButton

**Comment by anarkafkas** [comment]
I found that, for IOS, borderWidth works as expected but borderBottomWidth and borderTopWidth do not work. For Android, none of the three works.

**Comment by ribbit-rota** [comment]
Any update on this one?

**Comment by erickjth** [comment]
Same here

**Comment by guitexa** [comment]
not working on Android

**Comment by jakub-gonet** [comment]
`<RectButton />` is based on native `RNGestureHandlerButton` component which does implement `borderRadius` in a way that prevents using individual corners ([here's more info about that](https://github.com/software-mansion/react-native-gesture-handler/blob/1d23e205975e010d393bc164962ebcd1fd037031/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java#L126-L132)).

It also doesn't support setting `borderWidth`, nor `borderWidth`.

iOS implementation subclasses standard `RCTViewManager` class and supports every property that `<View />` supports.


Hard to say if it will be fixed in the near future, but I'll keep it in my issues-that-should-be-fixed-sometime list 🙂

**Comment by RBioZ** [comment]
same here

**Comment by leandrosouzaa** [comment]
> same here

try add the rect button inside a view.

**Comment by pauloels** [comment]
same here

**Comment by Gitarcitano** [comment]
Any update? Having the same problem here!

**Comment by euthribeiro** [comment]
This is because RectButton preserves the native shape of each platform. To solve this you can wrap your RectButton inside a View and style the View

**Comment by a-eid** [comment]
I'm wondering if there is any update on this. @jakub-gonet

**Comment by DenisDov** [comment]
i do that way:

```tsx
<RectButton
  hitSlop={16}
  style={{
    borderRadius: 14,
    backgroundColor: "white",
  }}
>
  <Box
    style={{
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: "#EAEAEA",
    }}
  >
    <Text>+</Text>
  </Box>
</RectButton>;

```
