### ISSUE TITLE
Make handlers on view corners

### ISSUE THREAD

**Issue by fouad1994** [software-mansion/react-native-gesture-handler#485]
Hello my friends
I need help
I want to make script like the image
I tried too many method but failed my case is I have a view size 5000x5000 scaled to become insight on the screen.
Inside this view user can add component with drag resize and rotate by touches.
and I need the icons like in the image one icon could rotate and resize.
I tried to use this:
https://kmagiera.github.io/react-native-gesture-handler

But dragging not correct its very very slow
And resizable when I end resize may component escape hhhhh

Please someone help me

![whatsapp image 2019-03-01 at 2 12 49 am](https://user-images.githubusercontent.com/35866405/53655584-71027400-3c05-11e9-904f-df5c2135c6a5.jpeg)

**Comment by asfwebmaster** [comment]
Have you found a solution on this? I am trying to create same functionality.

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.

**Comment by HenZzz-999** [comment]
@fouad1994 Hello, how are you :), from what I understand what you want is to create an area where the content does not appear, if so what you can do is the following, install the following libraries:
- For gestures: `'React Native Gesture Handler v2.x'`
- To move with the gesture: `'React Native Reanimated v3.x'`

Important information for calculating the limits of the area (Box):
- Size of the area (Box) (Width and Height)
- Image size (Content) (Width and Height)
- Spaces of difference (It is important for the limits to work):
     - Limits X: `((Box width - Content width) / 2)`
     - Limits Y: `((Box height - Content height) / 2)`

Taking this information into account we now declare the values:
```
const translate_content_X = useSharedValue(0);
const translate_content_Y = useSharedValue(0);

const box_width = useSharedValue(WIDTH)
const box_height = useSharedValue(HEIGHT)

const content_width = useSharedValue(WIDTH)
const content_height = useSharedValue(HEIGHT)

const limits_X = useSharedValue((box_width - content_width) / 2)
const limits_Y = useSharedValue((box_height - content_height) / 2)
```

Now in order to prevent it from leaving the box, you create your displacement function, here comes the important thing:
```
const panDisplacementGesture = Gesture.Pan()
.onChange((event) => {
   // Use the following events and also use the javascript Math() object simultaneously with the animation
   translate_content_X.value += event.changeX
   translate_content_X.value = Math.min(Math.max(translate_content_X.value, -limits_X.value), limits_X.value);

   translate_content_Y.value += event.changeY
   translate_content_Y.value = Math.min(Math.max(translate_content_Y.value, -limits_Y.value), limits_Y.value);
})
```
Change the values of `(-limits_X.value / limits_X.value)` and `(-limits_Y.value / limits_Y.value)` depending on where you place the Content.

The Math() object will directly limit the animation to where the 'Content' will move maximum and minimum.

I hope I have helped if you have any questions please send them to me :).
