### ISSUE TITLE
Expo demo not working

### ISSUE THREAD

**Issue by peterkuiper** [software-mansion/react-native-gesture-handler#529]
The Expo [demo](https://expo.io/@osdnk/gesturehandlerexample) is not working:

![IMG_0732](https://user-images.githubusercontent.com/6492184/54667513-d652d200-4aec-11e9-93ad-76c77b1b980c.PNG)

Can you share the build process for the Expo demo? This way the demo can be tested a bit easier by running it locally.

**Comment by maebert** [comment]
Same here, seems to be a permission issue?

**Comment by peterkuiper** [comment]
@osdnk Can you fix this? Or is there anything I can do to help?

**Comment by felixaa** [comment]
Probably a permission issue here. Can't clone it either.////
Would gladly help if possible

**Comment by RWOverdijk** [comment]
Under the same title, I'd like to mention that on android it says "This project uses SDK v27.0.0, but this Expo client requires at least v33.0.0"

**Comment by fredrivett** [comment]
A year on, no comment from anyone working on this repo, which is a bit awkward for a project that says it's supported by Expo and is on [Expo's docs](https://docs.expo.io/versions/latest/sdk/gesture-handler/). Especially that its on release 27 (10 major releases ago).

Can only guess this project is dead and one to be avoided.

**Comment by osdnk** [comment]
@fredrivett sure, you can. What’s the purpose?

You can also submit a PR fixing it and I’m pretty sure it will be more effective than complaining.

**Comment by fredrivett** [comment]
Hey @osdnk, thanks for the reply.

Agreed fixing it would be the most effective solution, but with no sign that the maintainers of this library think this is a problem (with multiple issues being raised over a period of a year with no comment from any maintainer), I'd hope why you can see this doesn't exactly signal "contributions desired".

I'm pretty new to React Native, only have experience with Expo and this isn't an area I can easily contribute on. If the fix is relatively simple and you can point me in the right direction I'm happy to take a look.

Am I right to assume this issue isn't being actively worked on right now?

**Comment by jakub-gonet** [comment]
Should be resolved by #1131
