### ISSUE TITLE
<RectButton> border radius behaves differently than in <View>

### ISSUE THREAD

**Issue by jalooc** [software-mansion/react-native-gesture-handler#562]
_NOTE: This is **not** the same issue as in #226_

**System:** iPhone 5s (simulator), iOS 12.2 (the problem doesn't appear on Android)
**RN Version:** 0.59.4
**react-native-gesture-handler version**: 1.1.0

For _small_ border radiuses (`borderRadius: 10` on screenshot), both components look identical:

![image](https://user-images.githubusercontent.com/6209244/56080042-3bec6280-5dfc-11e9-9eda-9926ecec100d.png)

However, _big_ border radiuses (`borderRadius: 100` on screenshot) overlap in `<RectButton>` differently than in `<View>`. In the first one, they create this pointy effect, in the latter, they form a smooth, rounded edge (which is obviously the desired behaviour):

![image](https://user-images.githubusercontent.com/6209244/56080048-4e669c00-5dfc-11e9-9edf-1174d0dca512.png)

**Comment by kesha-antonov** [comment]
Any solution?

**Comment by gustavopch** [comment]
This bug still exists. I was using the built-in buttons from React Native and used `borderRadius: 999` when I wanted a rounded corner regardless of the button size. Now that I'm refactoring to use the buttons from `react-native-gesture-handler`, `borderRadius: 999` can't be used because it doesn't render correctly on iOS.

**Comment by ArthurTriis1** [comment]
Same issue on 2.4.2

**Comment by versten1uk** [comment]
Still reproduced in `2.24.0`
