### ISSUE TITLE
PanGestureHandler doesn't work with WebView as child 

### ISSUE THREAD

**Issue by allthetime** [software-mansion/react-native-gesture-handler#648]
Hi, I'm working only on iOS right now and when I put a `WebView` (react-native-webview) in a `PanGestureHandler`, I get no response from `onGestureEvent`.

If I put a normal, empty `View` inside, I get data from `onGestureEvent`

react-native v0.59.9
react-native-gesture-handler v1.3.0

**Comment by allthetime** [comment]
```
  _onPanGestureEvent = () => {
    log('got something')
  }

  _render_web_view = () => {
       return <WebView 
         style={{
           marginTop: 20,
           height: height,
           width: width,
         }}
         scrollable={false}
         source={ require('./canvas.html') }
       />
  }

  _render_empty_view = ()=> {
    return<View
      style={ styles.container }
    />
  }

  render() {
    return (
      <PanGestureHandler
        onGestureEvent={this._onPanGestureEvent}>      
        {  this._render_web_view() }
       {  /* this._render_empty_view()*/ }
     </PanGestureHandler>
    );
  }
```

**Comment by allthetime** [comment]
Wrapping the WebView in another View with `flex:1` works, but why doesn't it work without a wrapper?

**Comment by viviangledhill** [comment]
seeing the same thing - though wrapping the WebView with a View and `flex:1` does not help for me

**Comment by DomiR** [comment]
The flex:1 workaround seems to work for iOS but not for Android. Although we can add a FlingGestureHandler a single-tap does not work as expected on android. The webview will focus links but will not follow them when tapping. Do you have a workaround for this as well?

**Comment by pjay79** [comment]
Seeing same issue with WebView as child for PanGestureHandler, getting no response from onGestureEvent or onHandlerStateChange. Wrapping in View does not work for me.

**Comment by jakub-gonet** [comment]
Could you please provide a small code example showing this problem?

**Comment by andmau90** [comment]
I think that the issue is inside alghoritm that check the child inside ViewGroup that can handle the touch but WebView on android is a ViewGroup without child so is skipped.

**Comment by jakub-gonet** [comment]
What happens if you wrap `WebView` with `NativeViewGestureHandler`?

**Comment by mikos** [comment]
Has anyone managed to get this working? I'm trying to add a WebView to the BottomSheet example but haven't had any luck.

**Comment by shahabt24** [comment]
> Has anyone managed to get this working? I'm trying to add a WebView to the BottomSheet example but haven't had any luck.

yes, me too. I tried any way to handle this but i can't find a solution

**Comment by aditya1711** [comment]
For me pan gestures to be handled by web view is not working when nested inside a pan gesture handler.

Any solutions for this issue?

**Comment by Jonovono** [comment]
Anyone figure a solution to this?

**Comment by princefishthrower** [comment]
Ring ring from 2022... anyone have a solution?

**Comment by andmau90** [comment]
i found a solution about my specific case.
`
<TapGestureHandler
    onHandlerStateChange={({ nativeEvent }) => {
        const { state, x, y } = nativeEvent;
        if (state === State.ACTIVE && this.webviewRef) {
            try {
                const node = findNodeHandle(this.weviewRef);
                await NativeModule.dispatchTap(node, x, y);
            } catch (e) {
                logWarn(e.message);
            }
        }
    }}
>
    <WebView ref={(ref) => this.webviewRef = ref}/>
</TapGestureHandler>
`

where NativeModule.dispatchTap is a java code that simply simulate the user tap on the webview
`
@ReactMethod
public void dispatchTap(int viewTag, float x, float y, Promise promise){
    try {
        final UIManagerModule uiManager = getReactApplicationContext().getNativeModule(UIManagerModule.class);
        uiManager.addUIBlock(nativeViewHierarchyManager -> {
            try {
                View view = nativeViewHierarchyManager.resolveView(viewTag);
                // List of meta states found here: developer.android.com/reference/android/view/KeyEvent.html#getMetaState()
                MotionEvent me;
                me = MotionEvent.obtain(SystemClock.uptimeMillis(), SystemClock.uptimeMillis() + 50, MotionEvent.ACTION_DOWN, x, y, 0);
                view.dispatchTouchEvent(me);
                me = MotionEvent.obtain(SystemClock.uptimeMillis() + 100, SystemClock.uptimeMillis() + 150, MotionEvent.ACTION_UP, x, y, 0);
                view.dispatchTouchEvent(me);
                promise.resolve("dispatched");
            } catch (Exception e){
                e.printStackTrace();
                promise.reject(e);
            }
        });
    } catch (Exception e){
        e.printStackTrace();
        promise.reject(e);
    }
}
`

i'm aware that is not a clean solution but in my case works well and achieves the purpose

**Comment by tomekzaw** [comment]
With react-native-gesture-handler v1, you need `NativeViewGestureHandler` in order to be able to receive events from native views (e.g. `WebView`, `ScrollView`, `TextInput`). This is also what @jakub-gonet has suggested a long time ago.

Basically, you need to make a HOC (higher-order component) using `createNativeWrapper` function. For convenience, react-native-gesture-handler also exports such HOCs for built-in React Native components, e.g. `ScrollView`, `Switch` or `TextInput`, see here:

https://github.com/software-mansion/react-native-gesture-handler/blob/4fb4e794411c20e134ab2d73eb9a01c98d313c13/src/components/GestureComponents.tsx#L47

However, `WebView` is not a built-in React Native component (as it comes from react-native-webview which is a third-party library). In order to be able to use it with react-native-gesture-handler, you need to make a RNGH-enabled HOC using `createNativeWrapper`:

```ts
const RNGHWebView = createNativeWrapper<WebViewProps>(WebView); 
```

> Wrapping the WebView in another View with `flex:1` works, but why doesn't it work without a wrapper?

Wrapping `WebView` with `<View style={{flex: 1}}>` works on iOS, because gesture handler attaches to `View` instead of `WebView`. It will also set `collapsable={false}` so the view won't get flattened. However, it doesn't seem to work on Android due to the fact that the implementation of react-native-gesture-handler is obviously platform-specific and uses a different approach than on iOS.

I don't recommend simulating touches using `injectJavaScript` or `dispatchTouchEvent` due to performance reasons.

> Ring ring from 2022...

With react-native-gesture-handler v2, you can use `<GestureDetector>` and `Gesture.Native()` from the new API (see [docs](https://docs.swmansion.com/react-native-gesture-handler/docs/api/gestures/native-gesture)).

**Comment by Darren120** [comment]
ring ring 2023
