### ISSUE TITLE
hitSlop on BorderlessButton not working as expected on real devices

### ISSUE THREAD

**Issue by mydesweb** [software-mansion/react-native-gesture-handler#682]
Setting hitSlop prop on a BorderlessButton seems to work fine on iOS Simulator but on physical does not behave in the same way.. in this example setting right: 16 has no effect, I have to increase it much more (x2) in order to make it work, but on Simulator is working as expected

"react-native-gesture-handler": "^1.3.0"

` 
<BorderlessButton
            style={{width: 44, height: 44, justifyContent: 'center', alignItems: 'center' }}
            onPress={this._onPress}
            hitSlop={{top: 0, left: 8, bottom: 0, right: 16}}>
            <View accessible>
                <Icon name="menu" size={24} color="#900"/>
            </View>
        </BorderlessButton>
`

**Comment by kmagiera** [comment]
hey @mydesweb – I'm sorry for lack of response on this one. I know that since this issue has been reported we have fixed a number of issues related to hitSlop prop. If you are still interested in this topic would you be able to verify if this problem still persist on the recent version? That'd help us a lot in filtering issues that are still current. Thanks!

**Comment by Sanaruca** [comment]
I have this problem using version `2.12.1`
