### ISSUE TITLE
Set cursor to the grabbing hand when gesture is active

### ISSUE THREAD

**Issue by EvanBacon** [software-mansion/react-native-gesture-handler#700]
😎

```css
cursor: grab;
```

**Comment by Warus15** [comment]
Added in [2.6.1](https://github.com/software-mansion/react-native-gesture-handler/releases/tag/2.6.1) 😎

Note that this change is available in new web implementation. To enable it, call `enableExperimentalWebImplementation()` in the root of your project.

**Comment by TomSwift** [comment]
Why is this desirable?   I just encountered the behavior and I don't want it, and not seeing a way to turn it off.

**Comment by chriscoomber** [comment]
@TomSwift I agree, and I've come up with a workaround to turn it off:

- Find the view that your `GestureDetector` wraps and get a `ref` to it.
- In every gesture's `onBegin`, set `viewRef.current.style.cursor = 'auto';`

For example:

```typescript
const viewRef = useRef<Animated.View>(null);

/* ... */

const panGesture = Gesture.Pan()
  .onBegin(() => {
    // Web fix: don't use the grabby hand when drawing.
    if (Platform.OS === 'web' && viewRef.current !== null) {
      (viewRef.current as unknown as HTMLElement).style.cursor = 'auto';
    }
  })
  /* ...more config */;

/* ... */

<GestureDetector gesture={panGesture}>
  <Animated.View ref={viewRef} /* ...more props */>
```

This works because they set the cursor to `'grab'` right after calling `activate()`, and I think that's always followed by the state being transitioned to `BEGIN`.

**Comment by m-bert** [comment]
Hi @TomSwift and @chriscoomber! We understand that this change may not be desirable and not everyone likes the idea. With that in mind I've prepared [this PR](#2550), which adds `activeCursor` prop. This way cursor keeps default appearance and if you would like to change it, you can use new prop to give it any css cursor value you'd like. I hope this will help!
