### ISSUE TITLE
TouchableOpacity onPress doesn't fire on web

### ISSUE THREAD

**Issue by elie222** [software-mansion/react-native-gesture-handler#787]
When using `TouchableOpacity` from RNGH on web, attaching an `onPress` to it won't do anything.

I'm using `TouchableOpacity` from `react-native` as workaround while on web.

**Comment by EvanBacon** [comment]
This might be related to #881

**Comment by EvanBacon** [comment]
Unfortunately I cannot reproduce this error: [example of it working in Expo snack](https://snack.expo.io/@bacon/rngh-787---touchableopacity-). I would imagine that the issue is related to your Webpack config. If it isn't configured properly it will resolve `TouchableOpacity.js` instead of `TouchableOpacity.web.js`. I recommend using `@expo/webpack-config` as it's setup to handle this. If you are still having this issue please provide a repro so I can investigate.
