### ISSUE TITLE
ios Crash on release build

### ISSUE THREAD

**Issue by jimji1005** [software-mansion/react-native-gesture-handler#820]
Crash still occurs while on release build with version 1.5.0

Verified on device, as well as on sim.

Issue occurs release build only.

See repo https://github.com/jimji1005/testGestureIOSReleaseCrash

```
clone
yarn
pod install
react-native run-ios --configuration Release
```

![gesture-crash](https://user-images.githubusercontent.com/5834998/68047242-1d1bc380-fc9b-11e9-98fc-c910868c5bfb.gif)

```
2019-11-01 11:14:15.633 [info][tid:main][RNGestureHandlerManager.m:136] [GESTURE HANDLER] Initialize gesture handler for root view <RCTRootContentView: 0x145d0a030; reactTag: 1; frame = (0 0; 375 667); gestureRecognizers = <NSArray: 0x2819e11d0>; layer = <CALayer: 0x281787f60>>
2019-11-01 11:14:25.585 [error][tid:com.facebook.react.JavaScript] Invariant Violation: Unsupported top level event type "onGestureHandlerStateChange" dispatched
2019-11-01 11:14:25.589 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Invariant Violation: Unsupported top level event type "onGestureHandlerStateChange" dispatched
2019-11-01 11:14:25.591909-0700 testGestureIOSReleaseCrash[868:64856] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Invariant Violation: Unsupported top level event type "onGestureHandlerStateChange" dispatched', reason: 'Unhandled JS Exception: Invariant Violation: Unsupported top level event type "onGestureHandlerStateChange" dispatched, stack:
extractEvents@94:13054
<unknown>@94:13845
_e@94:88659
Ne@94:13582
Ue@94:13755
receiveEvent@94:14164
value@24:3685
<unknown>@24:841
value@24:2939
value@24:813
value@<null>:<null>
'
*** First throw call stack:
(0x1a4bdf278 0x1a49080a4 0x104439f00 0x1044abf18 0x1a4be52b0 0x1a4ab54e8 0x1a4ab60a4 0x10446c9a8 0x10446eac8 0x10446e82c 0x1048e18ac 0x1048e2c88 0x1048e9bf8 0x1048ea794 0x1048f5b88 0x1a48fcfa8 0x1a48ffae4)
libc++abi.dylib: terminating with uncaught exception of type NSException```

**Comment by jimji1005** [comment]
info
```info Fetching system and libraries information...
System:
    OS: macOS 10.15.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 591.02 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.3 => 0.61.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by tallen11** [comment]
Any update on when this will be fixed?

**Comment by aazcast** [comment]
I am having the same problem, without solution, i try everything

**Comment by kyaroru** [comment]
Getting same crash on TestFlight build for **iOS 13.2** even after updating to v1.5.0 😢 But it works fine in Debug build

*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Invariant Violation: Unsupported top level event type "onGestureHandlerStateChange" dispatched', reason: 'Unhandled JS Exception: Invariant Violation: Unsupported top level event type "onGestureHandlerStateChange" dispatched, stack:
extractEvents@94:13054
<unknown>@94:13845
_e@94:88659
Ne@94:13582
Ue@94:13755
receiveEvent@94:14164
value@24:3685
<unknown>@24:841
value@24:2939
value@24:813
value@<null>:<null>
'
*** First throw call stack:
(0x1c3fcbab0 0x1c3ce5028 0x1028e1564 0x102952eb8 0x1c3fd25a4 0x1c3e9b1d0 0x1c3e9bde0 0x102913d08 0x102915e18 0x102915b7c 0x1c3c70b7c 0x1c3c71fd8 0x1c3c78450 0x1c3c78e7c 0x1c3c81f20 0x1c3cd7a94 0x1c3cddc7c)

**Comment by kyaroru** [comment]
Problem fixed after following this method: https://github.com/kmagiera/react-native-gesture-handler/issues/783#issuecomment-544974606 (But must ensure update to v1.5.0 & apply this method)

**Comment by jakub-gonet** [comment]
Seems resolved, so closing.
