### ISSUE TITLE
activeOffsetY ignored for handlerStateChange event on Android

### ISSUE THREAD

**Issue by franzwarning** [software-mansion/react-native-gesture-handler#913]
If I set activeOffsetY to [-10, 10] and tap the `PanGestureHandler` on iOS, no handlerStateChange event is called. If I do the same on Android, the handlerStateChange event is called twice. Is this expected behavior?

**Comment by j-piasecki** [comment]
Hi! This is indeed expected behavior. When you tap `PanGestureHandler` it transitions to the `BEGAN` state (meaning that it started tracking the finger and it's possible that the gesture will be recognized), and when you lift the finger it transitions to the `FAILED` state (meaning that the gesture was not recognized). If you want to make sure that the gesture was recognized you need to check if it's in the `ACTIVE` state.

Alternatively, you can use the new API introduced in Gesture Handler 2.0, where the state logic is handled under the hood, exposing callbacks for gesture lifecycle: `onBegin` callback is called when the gesture starts tracking its first pointer, and `onStart` is called when the gesture activates (it was recognized). You can learn more about it here: https://docs.swmansion.com/react-native-gesture-handler/docs/api/gestures/pan-gesture#callbacks-common-to-all-gestures.
