### ISSUE TITLE
Touchables onPress events are not forwarded

### ISSUE THREAD

**Issue by lcospain** [software-mansion/react-native-gesture-handler#926]
Inside the [GenericTouchable](https://github.com/software-mansion/react-native-gesture-handler/blob/master/touchables/GenericTouchable.js#L213) I noted the original event is not forwarded to the onPress handler. Is it the desired behavior ? Because I have an use case where switching from react-native to RNGH is a breaking change, and I think it should at least be mentionned in the [docs](https://software-mansion.github.io/react-native-gesture-handler/docs/component-touchables.html). I use a react-router-native link which is expecting a native event to be forwarded like so :

`<Link
    to={to}
    component={linkProps => (<TouchableOpacity {...linkProps} />)}
`

**Comment by jakub-gonet** [comment]
We _can_ forward it but those events are different: RN sends [an enormous object](https://snack.expo.io/C8w6m0Xtu) as an event and we send [only a few props](https://github.com/software-mansion/react-native-gesture-handler/blob/231103a8dc2ec07f11722384a60d0bc75575a18b/src/handlers/gestureHandlers.ts#L18).

If still relevant since (I'm replying a year late): does `react-router-native` work when you patch RNGH directly in node_modules to send event?

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply.

**Comment by tbigham** [comment]
@jakub-gonet At the risk of digging up a long-dead thread, what would be involved in creating a local patch to pass that RN touch event payload?  I've got a somewhat niche case that I'm trying to solve for which I don't think justifies a formal change on RNGH's side, but it's pretty clear from some of the comments scattered around GenericTouchable that it was something that was considered at the time of the TS rewrite.  Unfortunately, I'm not finding a place where I can begin grabbing that touch event data to pipe through.
