### ISSUE TITLE
[question] removing Swipable component from list

### ISSUE THREAD

**Issue by take** [software-mansion/react-native-gesture-handler#939]
hi thanks for the awesome library :bow: 

I have one question, I was looking at the [document of `Swipable`](https://software-mansion.github.io/react-native-gesture-handler/docs/component-swipeable.html), and looks like there are no APIs for removing the component itself from the list 🤔 

Are there any ways to do it? :eyes:

**Comment by kopax** [comment]
Hi and thanks also for this library, I have the same question here.

**Comment by Naturalclar** [comment]
Weather the component is swipeable or not, the way to remove something from a list is by actually removing what you want to remove from an array or however way you are holding the list item.

How I use it is by placing swipeable component inside a FlatList, and use functions like Array.filter to filter out the item to be removed on a swipe action.

I have an example in this repo, hope that helps :)
https://github.com/Naturalclar/react-native-swipe-list

**Comment by kopax** [comment]
Hi @Naturalclar , I am experiencing issue with the default sample, which is not happening on snack: https://snack.expo.io/@kopax/react-native-gesture-handler-issue-960

This snack work in expo, but it is not working with expo client on Samsung Galaxy S9.

I have reported this error in https://github.com/software-mansion/react-native-gesture-handler/issues/960

Have you experienced similar issue? I am about to use a web view for all my android users because of it. 

Thanks for sharing the example, I will have a try and I'll hope it will be working on Android this one.

**Comment by take** [comment]
@Naturalclar 

thx i'll try it out :)

**Comment by kopax** [comment]
I finally succeed not to rerender my list. The trick was to just hide to `height 0 ` the line and keep the array as it was at the beggining.

This prevent the list size from changing and rerendering.
